<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ecrmac-100510.local" ignored="2" name="sandbox" tests="6" failures="1" timestamp="08 Oct 2018 19:17:27 GMT" time="91.827" errors="0">
  <testcase name="@AfterMethod after" time="0.001" classname="tests.InvoiceTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at tests.InvoiceTest.after(InvoiceTest.java:38)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod after -->
  <testcase name="@AfterMethod getResult" time="0.0" classname="reports.ExtentReportsClass">
    <skipped/>
  </testcase> <!-- @AfterMethod getResult -->
  <testcase name="@AfterTest endReport" time="0.0" classname="reports.ExtentReportsClass">
    <skipped/>
  </testcase> <!-- @AfterTest endReport -->
  <testcase name="loginComSucesso" time="16.233" classname="tests.Login"/>
  <testcase name="autenticaFalha" time="16.117" classname="tests.Login"/>
  <testcase name="autenticaFalha" time="17.421" classname="tests.Login"/>
  <testcase name="autenticaFalha" time="18.828" classname="tests.Login"/>
  <testcase name="autenticaFalha" time="10.123" classname="tests.Login"/>
  <testcase name="autenticainvoice" time="0.002" classname="tests.InvoiceTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at tests.InvoiceTest.autenticainvoice(InvoiceTest.java:46)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- autenticainvoice -->
  <testcase name="@BeforeTest startTest" time="0.0" classname="reports.ExtentReportsClass">
    <ignored/>
  </testcase> <!-- @BeforeTest startTest -->
  <testcase name="@AfterTest endReport" time="0.0" classname="reports.ExtentReportsClass">
    <ignored/>
  </testcase> <!-- @AfterTest endReport -->
</testsuite> <!-- sandbox -->
